package com.c2086696.cm3203.Controller;

import com.c2086696.cm3203.Entity.User;
import com.c2086696.cm3203.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping("/login")
    public String login(){
        return"login";
    }

    @GetMapping("/signin")
    public String signin(){
        return"signIn";
    }

    @GetMapping("/hello")
    public String hello(){
        return"hello";
    }

    @GetMapping("/home")
    public String home(){
        return"home";
    }

    @GetMapping("/welcome")
    public String wlecome(){
        return"welcome";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

}
